services:
  cloudflare-ddns:
    restart: always
    container_name: cloudflare-ddns
    image: timothyjmiller/cloudflare-ddns:latest
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    environment:
      CLOUDFLARE_API_TOKEN_FILE: /run/secrets/cloudflare-api-token
      DOMAINS: server.coder2195.dev
    secrets:
      - cloudflare-api-token

  postgres-db:
    restart: always
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_USER: coder2195
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/
      - ./postgresql:/etc/postgresql-config/
    command: postgres -c config_file=/etc/postgresql-config/postgresql.conf
    secrets:
      - postgres-password

  caddy:
    restart: always
    container_name: caddy
    image: caddy:latest
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/:/etc/caddy/
      - ./site:/var/www/html
      - caddy-data:/data
      - caddy-config:/config

  minecraft-proxy:
    restart: always
    container_name: minecraft-proxy
    image: itzg/mc-proxy
    environment:
      TYPE: VELOCITY
      REPLACE_ENV_VARIABLES: "true"
      CFG_MOTD: "Server hosted by &4&kaaa&k &4&lAmber &kaaa&k&r

        Like the server? support at &b&nko-fi.com/coder2195"
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft/velocity.toml:/config/velocity.toml
      - ./secrets/velocity-secret.txt:/config/forwarding.secret
      - minecraft-proxy:/server

  minecraft-setup:
    container_name: minecraft-setup
    build: ./minecraft/
    volumes:
      - amber-smp:/amber-smp
      - pumpkin-anarchy:/pumpkin-anarchy
      - ./minecraft/pumpkin-anarchy:/template/pumpkin-anarchy
      - ./minecraft/amber-smp:/template/amber-smp
    secrets:
      - velocity-secret
      - rcon-password

  amber-smp:
    depends_on:
      minecraft-setup:
        condition: service_completed_successfully
        restart: true
    restart: always
    container_name: amber-smp
    image: itzg/minecraft-server:latest
    volumes:
      - amber-smp:/data
      - ./minecraft/amber-smp/server.properties:/data/server.properties
    environment:
      TYPE: LEAF
      VERSION: 26.2
      ONLINE_MODE: FALSE
      EULA: TRUE
      DEBUG: TRUE
      SYNC_SKIP_NEWER_IN_DESTINATION: false

  pumpkin-anarchy:
    depends_on:
      minecraft-setup:
        condition: service_completed_successfully
        restart: true
    ports:
      - "27000:25565"
    restart: always
    image: "ghcr.io/pumpkin-mc/pumpkin:latest"
    container_name: pumpkin-anarchy
    volumes:
      - pumpkin-anarchy:/pumpkin
    security_opt:
      - no-new-privileges:true
    stdin_open: true
    tty: true
    cap_drop:
      - ALL
    read_only: true

volumes:
  postgres-data:
  caddy-data:
  caddy-config:
  amber-smp:
  pumpkin-anarchy:
  minecraft-proxy:

secrets:
  cloudflare-api-token:
    file: secrets/cloudflare-api-token.txt
  postgres-password:
    file: secrets/postgres-password.txt
  velocity-secret:
    file: secrets/velocity-secret.txt
  rcon-password:
    file: secrets/rcon-password.txt
