services:
  cloudflare-ddns:
    restart: always
    container_name: cloudflare-ddns
    image: timothyjmiller/cloudflare-ddns:latest
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    environment:
      CLOUDFLARE_API_TOKEN_FILE: /run/secrets/cloudflare_api_token
      DOMAINS: server.coder2195.dev
    secrets:
      - cloudflare_api_token

  postgres-db:
    restart: always
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_USER: coder2195
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
      - ./postgresql:/etc/postgresql_config/
    command: postgres -c config_file=/etc/postgresql_config/postgresql.conf
    secrets:
      - postgres_password

  caddy:
    restart: always
    container_name: caddy
    image: caddy:latest
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/caddy/:/etc/caddy/
      - $PWD/site:/var/www/html
      - caddy_data:/data
      - caddy_config:/config


  minecraft-proxy:
    restart: always
    container_name: minecraft-proxy 
    image: itzg/mc-proxy
    environment:
      TYPE: VELOCITY
      REPLACE_ENV_VARIABLES: "true"
      CFG_MOTD: "Server hosted by &4&kaaa&k &4&lAmber &kaaa&k&r\nLike the server? support at &b&nko-fi.com/coder2195"
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft/velocity.toml:/config/velocity.toml
      - ./secrets/velocity_secret.txt:/config/forwarding.secret
      - minecraft_proxy:/server

  wic-smp:
    secrets:
      - velocity_secret
    restart: always
    container_name: wic-smp
    image: itzg/minecraft-server:latest
    volumes:
      - ./minecraft/global_patches.json:/config/global_patches.json
      - ./minecraft/paper-global.yml:/config/paper-global.yml
      - wic_smp:/data
    environment:
      TYPE: LEAF
      VERSION: 26.2
      ONLINE_MODE: FALSE
      EULA: TRUE
      DEBUG: TRUE
      SYNC_SKIP_NEWER_IN_DESTINATION: false
      PATCH_DEFINITIONS: "/config/global_patches.json"
      REPLACE_ENV_VARIABLES: "TRUE"
      # define an optional prefix for your env variables you want to replace
      ENV_VARIABLE_PREFIX: "CFG_"
      # and here are the actual variables
      CFG_VELOCITY_SECRET_FILE: "/run/secrets/velocity_secret"
   
volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  wic_smp:
  minecraft_proxy:

secrets:
  cloudflare_api_token:
    file: secrets/cloudflare_api_token.txt
  postgres_password:
    file: secrets/postgres_password.txt
  velocity_secret:
    file: secrets/velocity_secret.txt

